# Generated by Django 2.2.5 on 2020-10-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_thumbnail_url',
            field=models.TextField(),
        ),
    ]
